# Generated by Django 4.2.5 on 2023-09-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0002_alter_personalityprediction_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalityPrediction',
        ),
    ]
